server:
  port: 7070
#  tomcat:
#    uri-encoding: UTF-8
#    connection-timeout: 20000
#    keep-alive-timeout: 60000
#    threads:
#     max: 400
#     min-spare: 10
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/Easylive?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20          # 连接池最大连接数
        max-wait: -1            # 连接池最大阻塞等待时间
        max-idle: 10            # 连接池中的最大空闲连接
        min-idle: 0             # 连接池中的最小空闲连接
    timeout: 2000               # 连接超时时间（毫秒）

mybatis-plus:
    mapper-locations: classpath:/mappers/*.xml
servlet:
    multipart:
      # 限制单个文件的上传大小
      max-file-size: 30MB
      max-request-size: 30MB
      # 设置懒解析，提升上传性能
      resolve-lazily: true

